name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Docker and bring up the services
      - name: Set up Docker
        run: |
          docker compose -f compose.dev.yaml up -d --build

          # Verify that the environment variables are passed correctly to the Docker containers
          echo "Verifying environment variables in the server container:"
          docker compose exec server printenv | grep DATABASE_URL
          docker compose exec server printenv | grep SESSION_SECRET
          docker compose exec server printenv | grep GOOGLE_CLIENT_ID
          docker compose exec server printenv | grep GOOGLE_CLIENT_SECRET
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          API_URL: ${{ secrets.API_URL }}

      - name: Wait for services to be ready
        run: |
          sleep 30 

      # Run tests in the server
      - name: Run server tests
        id: server-tests
        run: |
          if ! docker compose -f compose.dev.yaml exec server pnpm test; then
            echo "Server tests failed. Fetching logs..."
            docker compose -f compose.dev.yaml logs server
            exit 1
          fi

      # Run tests in the client
      - name: Run client tests
        id: client-tests
        run: |
          if ! docker compose -f compose.dev.yaml exec web pnpm test; then
            echo "Client tests failed. Fetching logs..."
            docker compose -f compose.dev.yaml logs web
            exit 1
          fi
        continue-on-error: true

      # Stop and remove containers after tests
      - name: Tear down Docker
        run: docker compose -f compose.dev.yaml down

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Deploy
      uses: DefangLabs/defang-github-action@v1.1.0
