name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Docker and bring up the services
      - name: Set up Docker
      - env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          docker compose -f compose.dev.yaml up -d --build
          # Wait for services to be ready
          sleep 30 

      # Run tests in the server
      - name: Run server tests
        id: server-tests
        run: |
          if ! docker compose -f compose.dev.yaml exec server pnpm test; then
            echo "Server tests failed. Fetching logs..."
            docker-compose -f compose.dev.yaml logs server
            exit 1
          fi
      
      # Run tests in the client
      - name: Run client tests
        id: client-tests
        run: |
          if ! docker compose -f compose.dev.yaml exec client pnpm test; then
            echo "Client tests failed. Fetching logs..."
            docker-compose -f compose.dev.yaml logs client
            exit 1
          fi
        continue-on-error: true

      # stop and remove containers after tests
      - name: Tear down Docker
        run: docker-compose -f compose.dev.yaml down

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Deploy
      uses: DefangLabs/defang-github-action@v1.1.0